version: '3.7'
volumes:
  step3b_db:
  step3c_db:
  step3d_db:
  step4_db:
  step3c_msc4040_db:
  step4_msc4040_db:
networks:
  step3b:
  step3c:
  step3d:
  step4:
  step3c_msc4040:
  step4_msc4040:
secrets:
  step3b_db_passwd:
    file: secret_step3b_db_passwd.txt
  step3b_db_url:
    file: secret_step3b_db_url.txt

  step3c_db_passwd:
    file: secret_step3c_db_passwd.txt
  step3c_db_url:
    file: secret_step3c_db_url.txt

  step3d_db_passwd:
    file: secret_step3d_db_passwd.txt
  step3d_db_url:
    file: secret_step3d_db_url.txt

  step4_db_passwd:
    file: secret_step4_db_passwd.txt
  step4_db_url:
    file: secret_step4_db_url.txt

  step3c_msc4040_db_passwd:
    file: secret_step3c_msc4040_db_passwd.txt
  step3c_msc4040_db_url:
    file: secret_step3c_msc4040_db_url.txt

  step4_msc4040_db_passwd:
    file: secret_step4_msc4040_db_passwd.txt
  step4_msc4040_db_url:
    file: secret_step4_msc4040_db_url.txt
services:
  # --- Step 3b ---
  step3b_db:
    container_name: "step3b_db"
    image: "postgres:15"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "keyserver"
      POSTGRES_DB: "keyserver"
      POSTGRES_PASSWORD_FILE: "/run/secrets/step3b_db_passwd"
    volumes:
      - step3b_db:/var/lib/postgresql/data
    secrets:
      - step3b_db_passwd
    networks:
      - step3b
  step3b_keyserver:
    container_name: "step3b_keyserver"
    image: "t2bot/matrix-key-server:latest"
    restart: unless-stopped
    depends_on:
      - step3b_db
    environment:
      ADDRESS: "0.0.0.0"
      PORT: "8080"
      DOMAIN: "3b.s.resolvematrix.dev"
      POSTGRES: "/run/secrets/step3b_db_url"
    ports:
      - "127.0.0.1:7743:8080"
    secrets:
      - step3b_db_url
    networks:
      - step3b

  # --- Step 3c ---
  step3c_db:
    container_name: "step3c_db"
    image: "postgres:15"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "keyserver"
      POSTGRES_DB: "keyserver"
      POSTGRES_PASSWORD_FILE: "/run/secrets/step3c_db_passwd"
    volumes:
      - step3c_db:/var/lib/postgresql/data
    secrets:
      - step3c_db_passwd
    networks:
      - step3c
  step3c_keyserver:
    container_name: "step3c_keyserver"
    image: "t2bot/matrix-key-server:latest"
    restart: unless-stopped
    depends_on:
      - step3c_db
    environment:
      ADDRESS: "0.0.0.0"
      PORT: "8080"
      DOMAIN: "3c.s.resolvematrix.dev"
      POSTGRES: "/run/secrets/step3c_db_url"
    ports:
      - "127.0.0.1:7744:8080"
    secrets:
      - step3c_db_url
    networks:
      - step3c

  # --- Step 3d ---
  step3d_db:
    container_name: "step3d_db"
    image: "postgres:15"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "keyserver"
      POSTGRES_DB: "keyserver"
      POSTGRES_PASSWORD_FILE: "/run/secrets/step3d_db_passwd"
    volumes:
      - step3d_db:/var/lib/postgresql/data
    secrets:
      - step3d_db_passwd
    networks:
      - step3d
  step3d_keyserver:
    container_name: "step3d_keyserver"
    image: "t2bot/matrix-key-server:latest"
    restart: unless-stopped
    depends_on:
      - step3d_db
    environment:
      ADDRESS: "0.0.0.0"
      PORT: "8080"
      DOMAIN: "3d.s.resolvematrix.dev"
      POSTGRES: "/run/secrets/step3d_db_url"
    ports:
      - "127.0.0.1:7745:8080"
    secrets:
      - step3d_db_url
    networks:
      - step3d

  # --- Step 4 ---
  step4_db:
    container_name: "step4_db"
    image: "postgres:15"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "keyserver"
      POSTGRES_DB: "keyserver"
      POSTGRES_PASSWORD_FILE: "/run/secrets/step4_db_passwd"
    volumes:
      - step4_db:/var/lib/postgresql/data
    secrets:
      - step4_db_passwd
    networks:
      - step4
  step4_keyserver:
    container_name: "step4_keyserver"
    image: "t2bot/matrix-key-server:latest"
    restart: unless-stopped
    depends_on:
      - step4_db
    environment:
      ADDRESS: "0.0.0.0"
      PORT: "8080"
      DOMAIN: "4.s.resolvematrix.dev"
      POSTGRES: "/run/secrets/step4_db_url"
    ports:
      - "127.0.0.1:7845:8080"
    secrets:
      - step4_db_url
    networks:
      - step4

  # --- Step 3c [MSC4040] ---
  step3c_msc4040_db:
    container_name: "step3c_msc4040_db"
    image: "postgres:15"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "keyserver"
      POSTGRES_DB: "keyserver"
      POSTGRES_PASSWORD_FILE: "/run/secrets/step3c_msc4040_db_passwd"
    volumes:
      - step3c_msc4040_db:/var/lib/postgresql/data
    secrets:
      - step3c_msc4040_db_passwd
    networks:
      - step3c_msc4040
  step3c_msc4040_keyserver:
    container_name: "step3c_msc4040_keyserver"
    image: "t2bot/matrix-key-server:latest"
    restart: unless-stopped
    depends_on:
      - step3c_msc4040_db
    environment:
      ADDRESS: "0.0.0.0"
      PORT: "8080"
      DOMAIN: "3c.msc4040.s.resolvematrix.dev"
      POSTGRES: "/run/secrets/step3c_msc4040_db_url"
    ports:
      - "127.0.0.1:7144:8080"
    secrets:
      - step3c_msc4040_db_url
    networks:
      - step3c_msc4040

  # --- Step 4 [MSC4040] ---
  step4_msc4040_db:
    container_name: "step4_msc4040_db"
    image: "postgres:15"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "keyserver"
      POSTGRES_DB: "keyserver"
      POSTGRES_PASSWORD_FILE: "/run/secrets/step4_msc4040_db_passwd"
    volumes:
      - step4_msc4040_db:/var/lib/postgresql/data
    secrets:
      - step4_msc4040_db_passwd
    networks:
      - step4_msc4040
  step4_msc4040_keyserver:
    container_name: "step4_msc4040_keyserver"
    image: "t2bot/matrix-key-server:latest"
    restart: unless-stopped
    depends_on:
      - step4_msc4040_db
    environment:
      ADDRESS: "0.0.0.0"
      PORT: "8080"
      DOMAIN: "4.msc4040.s.resolvematrix.dev"
      POSTGRES: "/run/secrets/step4_msc4040_db_url"
    ports:
      - "127.0.0.1:7145:8080"
    secrets:
      - step4_msc4040_db_url
    networks:
      - step4_msc4040